"""Write a self-contained LaTeX source for upload to JAMIA.

The working source reads numbers and tables from ../revision/generated/, the
bibliography from BibTeX and supplement cross-references through xr. A journal
system compiling the upload would see none of those. This script writes
source_for_upload/main_jamia_r1.tex with every \\input inlined, the compiled
bibliography (.bbl) inlined, and each supplement reference resolved to its
printed label, so the file compiles on its own with pdflatex.

    python3 flatten.py      (run by build.sh after the manuscript is built)

source_for_upload/ is gitignored: it contains the corresponding author's
telephone number.
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "source_for_upload"


def inline_inputs(tex: str, base: Path) -> str:
    def repl(m: re.Match) -> str:
        name = m.group(1)
        path = (base / name)
        if path.suffix != ".tex":
            path = path.with_name(path.name + ".tex")
        return inline_inputs(path.read_text().rstrip("\n"), base)

    # \IfFileExists{private_phone.tex}{\input{private_phone.tex}\unskip}{...}
    phone = HERE / "private_phone.tex"
    tex = re.sub(
        r"\\IfFileExists\{private_phone\.tex\}\{\\input\{private_phone\.tex\}\\unskip\}\{[^}]*\}",
        lambda _: phone.read_text().strip() if phone.exists() else "withheld from the public repository",
        tex,
    )
    return re.sub(r"\\input\{([^}]+)\}", repl, tex)


def supplement_labels() -> dict[str, str]:
    labels = {}
    for line in (HERE / "supplement_jamia_r1.aux").read_text().splitlines():
        m = re.match(r"\\newlabel\{([^}@]+)\}\{\{([^}]*)\}", line)
        if m:
            labels[m.group(1)] = m.group(2)
    return labels


def main() -> int:
    tex = (HERE / "main_jamia_r1.tex").read_text()
    tex = inline_inputs(tex, HERE)

    labels = supplement_labels()
    missing = []

    def resolve(kind: str, key: str) -> str:
        if key not in labels:
            missing.append(key)
            return key
        word = "Supplementary Table" if kind == "stab" else "Supplementary Section"
        return f"{word}~{labels[key]}"

    tex = re.sub(r"\\(stab|ssec)\{([^}]+)\}", lambda m: resolve(m.group(1), m.group(2)), tex)
    tex = tex.replace("\\usepackage{xr-hyper}\n", "")
    tex = re.sub(r"\\externaldocument\[S-\]\{[^}]+\}\n", "", tex)
    tex = re.sub(r"\\newcommand\{\\(stab|ssec)\}\[1\]\{[^\n]*\}\n", "", tex)

    bbl = (HERE / "main_jamia_r1.bbl").read_text()
    tex = re.sub(r"\\bibliographystyle\{[^}]+\}\n", "", tex)
    tex = re.sub(r"\\bibliography\{[^}]+\}", lambda _: bbl.strip(), tex)

    if missing or re.search(r"\\input\{|\\bibliography\{|\\(stab|ssec)\{", tex):
        print(f"flatten: unresolved items {missing}", file=sys.stderr)
        return 1

    OUT.mkdir(exist_ok=True)
    header = (
        "% Self-contained source for the JAMIA upload, generated by flatten.py from\n"
        "% main_jamia_r1.tex. Compile with: pdflatex main_jamia_r1.tex (twice).\n"
    )
    (OUT / "main_jamia_r1.tex").write_text(header + tex)
    print(f"flatten: wrote {OUT.name}/main_jamia_r1.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
